config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root 'homes#index'
	resources :posts
	resources :profiles
	resources :users
	resources :arts
	namespace :admin do
		get "/", to: "homes#index"
		resources :posts
		resources :categories
		resources :users
		resources :arts
	end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/art.rb
class Art < ApplicationRecord
	has_one_attached :images
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	has_one_attached :image 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/arts_controller.rb
class Admin::ArtsController < ApplicationController
	def index
		@arts = Art.all
	end

	def new
		@art = Art.new
	end

	def create
		@art = Art.new(art_params)
		if @art.save
			redirect_to admin_arts_path
		end
	end

	private
	def art_params
		params.require(:art).permit(:images, :author)
	end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			redirect_to new_admin_category_path
		end
	end

	private
	def category_params
		params.require(:category).permit(:title)
	end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
	# before_action :authenticate_user!
	def index
		@post = Post.all
	end

	def new
		@post = Post.new
	end

	def show
		@post = Post.find(params[:id])
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			redirect_to admin_post_path(@post)
		end
	end

	def destroy
		@post = Post.find(params[:id])
		if
			@post.destroy
			redirect_to admin_posts_path
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		@post.update(post_params)
		redirect_to admin_post_path(@post)
	end

	private
	def post_params
		params.require(:post).permit(:title, :body)
	end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def destroy
		@user = User.find(params[:id])
		if
			@user.destroy
			redirect_to admin_users_path
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		@user.update(users_params)
		redirect_to admin_user_path(@user)
	end

	private
	def users_params
		params.require(:user).permit(:firsname, :email, :category)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:category, :firsname, :image ])
  end
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
	def index
		@arts = Art.all
	end

	def new
		@art = Art.new
	end

	def create
		@art = Art.new(art_params)
		if @art.save
			redirect_to arts_path
		end
	end

	private
	def art_params
		params.require(:art).permit(:images, :author)
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def index
		
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	# before_action :authenticate_user!
	def index
		@post = Post.all
	end

	def show
		@post = Post.find(params[:id])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@user = current_user
	end

	def edit
		@user = current_user
	end
	
	def update
		@user = current_user
		@user.update(user_params)
		redirect_to users_path(@user)
	end

	private
	def user_params
		params.require(:user).permit(:firsname, :email, :image)
	end
end

app/helpers/admin/arts_helper.rb
module Admin::ArtsHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/arts/index.html.erb
<br>
<% @arts.each do |art| %>
  <p><%= image_tag art.images %></p>
  <p><%= art.author %></p>
  <hr>
<% end %>

app/views/admin/arts/new.html.erb
<br>
<%= form_for [:admin, @art] do |f| %>
	<%= f.file_field :images %>
	<%= f.submit %>
<% end %>

app/views/admin/homes/index.html.erb
<br>
<h1 class="text-center">Admin panel</h1>

app/views/admin/posts/edit.html.erb
<br>
<%= form_for [:admin, @post] do |f| %>
	<%= f.text_field :title %>
	<%= f.text_field :body %>
	<%= f.submit %>
<% end %>

app/views/admin/posts/index.html.erb
<br>
<% @post.each do |post| %>
  <p>Name of post - <%= post.title %></p>
  <p>Name of post - <%= post.body %></p>
  <%= link_to "Read more", admin_post_path(post) %>
  <hr>
<% end %>

app/views/admin/posts/new.html.erb
<br>
<%= form_for [:admin,@post] do |f| %>
	<%= f.text_field :title %>
	<%= f.text_field :body %>
	<%= f.submit %>
<% end %>

app/views/admin/posts/show.html.erb
<br>
<%= @post.title %>
<%= @post.body %>
<%= link_to "delete", [:admin, @post] , method: :delete %>
<%= link_to "edit", edit_admin_post_path(@post) %>

app/views/admin/users/edit.html.erb
<br>
<div class="container-fluid">
	<table class="table table-striped">
		<tr>
			<th>Name</th>
			<th>Mail</th>
			<th>Category</th>
			<th>Actions</th>
	    </tr>
		<tr>
			<%= form_for [:admin, @user] do |f| %>
				<td><%= f.text_field :firsname %></td>
				<td><%= f.text_field :email %></td>
				<td ><%= select("user", :category, Category.all.collect {|p| [ p.title, p.title ] }, { include_blank: true })%></td>
				<td><%= f.submit %></td>
			<% end %>	
		</tr>
	</table>
</div>

app/views/admin/users/index.html.erb
<br>
<div class="container-fluid">
	<table class="table table-striped">
	<tr>
		<th>Name</th>
		<th>Category</th>
		<th>Action</th>
    </tr>
	<% @users.each do |user| %>
		<tr>
	      <td><%= user.firsname %></td>
	      <td class="text-capitalize"><%= user.category %></td>
	      <td><%= link_to "Change", admin_user_path(user) %></td>
    	</tr>
	<% end %>
</table>
</div>

app/views/admin/users/show.html.erb
<br>
<div class="container-fluid">
	<table class="table table-striped">
		<tr>
			<th>Firstname</th>	
			<th>Category</th>
			<th>Email</th>
			<th>Actions</th>
		</tr>
		<tr>
			<td><%= @user.firsname %></td>
			<td class="text-capitalize"><%= @user.category %></td>
			<td><%= @user.email %></td>
			<td>
			<%= link_to "Delete", [:admin, @user] , method: :delete, class: "btn btn-danger" %>
			<%= link_to "Edit", edit_admin_user_path(@user), class: "btn btn-warning" %>
			</td>
		</tr>
	</table>
</div>

app/views/arts/index.html.erb
<br>
<% @arts.each do |art| %>
	<% if art.images.present? %>
 		 <p><%= image_tag art.images %>
	<% else %>
		<img src="default_image.png">
 	<% end %>
  <br>
  <p><%= art.author %></p>
  <hr>
<% end %>

app/views/arts/new.html.erb
<br>
<%= form_for @art do |f| %>
	<%= f.file_field :images %>
	<br>
	<span>Your Name: </span> <%= f.text_field :author, value:current_user.firsname, class: "author_name" %>
	<br>
	<%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<br>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<%= form_for @user do |f| %>
				<%= f.text_field :firsname %>
				<%= f.text_field :email %>
				<%= f.file_field :image %>
				<%= f.submit %>
			<% end %>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="profile__info">
	<p><%= @user.category %></p>
	<p><%= @user.firsname %></p>
	<p><%= @user.email %></p>
	<%= link_to 'edit', edit_user_path(@user) %>
	<% if current_user.image.present? %>
		<%= image_tag (@user.image), class: "profile__image" %>

	<% else %>
		<img class="profile__image" src="default_image.png">
	<% end %>
	
</div>