config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root 'homes#index'
	resources :posts
	resources :profiles
	resources :users
	resources :arts
	namespace :admin do
		get "/", to: "homes#index"
		resources :posts
		resources :categories
		resources :users
		resources :arts
	end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/art.rb
class Art < ApplicationRecord
	has_one_attached :images
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	has_one_attached :image 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/arts_controller.rb
class Admin::ArtsController < ApplicationController
	def index
		@arts = Art.all
	end

	def new
		@art = Art.new
	end

	def create
		@art = Art.new(art_params)
		if @art.save
			redirect_to admin_arts_path
		end
	end

	private
	def art_params
		params.require(:art).permit(:images, :author)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:category, :firsname, :image ])
  end
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
	def index
		@arts = Art.all
	end

	def new
		@art = Art.new
	end

	def create
		@art = Art.new(art_params)
		if @art.save
			redirect_to arts_path
		end
	end

	private
	def art_params
		params.require(:art).permit(:images, :author)
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def index
		
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	# before_action :authenticate_user!
	def index
		@post = Post.all
	end

	def show
		@post = Post.find(params[:id])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@user = current_user
	end

	def edit
		@user = current_user
	end
	
	def update
		@user = current_user
		@user.update(user_params)
		redirect_to users_path(@user)
	end

	private
	def user_params
		params.require(:user).permit(:firsname, :email, :image)
	end
end

app/helpers/admin/arts_helper.rb
module Admin::ArtsHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <%= link_to "Home Admin", admin_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <% if current_user %>
        <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, data: {method: :delete}, class: "nav-link" %>
        </li>
         <li class="nav-item active">
          <%= link_to "New Posts", new_admin_post_path, class: "nav-link"%>
        </li> 
      <% else %>

        <li class="nav-item active">
          <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
        </li>


        <li class="nav-item active">
          <%= link_to "Registration", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>

      <% if current_user.category == "admin" %>
        <li class="nav-item active">
          <%= link_to "Posts", admin_posts_path, class: "nav-link"%>
        </li>

        <li class="nav-item active">
          <%= link_to "Users", admin_users_path, class: "nav-link"%>
        </li>

        <li class="nav-item active">
          <%= link_to "Gallery", admin_arts_path, class: "nav-link"%>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appl</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <% if controller_path =~ /^admin\// %>
        <%= render  "admin/shared/header" %>  

      <% else %>
        <%= render "shared/header" %>
      <% end %>

    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if current_user %>
       <%= link_to "Posts", posts_path, class: "navbar-brand" %>
       <%= link_to "Log out", destroy_user_session_path, data: {method: :delete}, class: "nav-link" %>
       <%= link_to "Gallery", arts_path, class: "nav-link" %>
       <% if current_user %>
       <%= link_to "Profile", users_path, class: "nav-link" %>
       <% end %>
      <% else %>
        <li class="nav-item active">
          <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
        </li>

        <li class="nav-item active">
          <%= link_to "Registration", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>

      <% if current_user && current_user.category != "user" %>
        <%= link_to "Admin panel", admin_path, class: "nav-link" %>
      <% end %>

    </ul>
  </div>
</nav>